---

# Deployes Rue89 staging instance.

- name: Configure instance(s)
  hosts: stage
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    ENABLE_LEGACY_ORA: !!null
  roles:
    - aws
    - security
    - postfix_queue
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - notifier
    - edx_notes_api
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - certs
    - edx_ansible
