---

# Deploys Rue89 edxapp instances.

- name: Configure instance(s)
  hosts: app
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: False
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    ENABLE_LEGACY_ORA: !!null
  roles:
    - aws
    - security
    - postfix_queue
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - notifier
    - edx_notes_api
    - oraclejdk
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - role: ora
      when: ENABLE_LEGACY_ORA
    - certs
    - edx_ansible
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
  tasks:
    - name: install packages needed for single server
      apt: pkg="postfix,libjpeg-dev" install_recommends=yes state=present
    - name: script for offline grade calculation
      copy:
        src: "./rue89/edxapp-compute-grades"
        dest: "/edx/bin/edxapp-compute-grades"
        owner: edxapp
        mode: 0755
    - name: cronjob for offline grade calculation
      cron:
        name: "cronjob for offline grade calculation"
        user: root
        hour: 1
        minute: 0
        job: "/edx/bin/edxapp-compute-grades > /dev/null 2>&1"
